version: '3.8'

services:
  # --rm and -d flags are composer's default
  # composer also automatically generates the containers' network
  mysqldb:
    image: 'mysql:8.0.29'
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_docker
      - MYSQL_DATABASE=node_store_db
    ports:
      - '3306:3306'
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  node-store:
    build: ./
    ports:
      - '3000:3000'
    env_file: ./.env
    depends_on:
      - mysqldb